trigger:
- main

schedules:
- cron: "0 0 * * 3"
  always: true
  branches:
    include:
    - main

parameters:
  - name: SkipLinux
    default: false
    type: boolean
    displayName: Skip Linux

variables:
  - template: variables/build.yml

appendCommitMessageToRunName: false

jobs:
- job: Build
  strategy:
    matrix:
      ${{ if eq(parameters.SkipLinux, false) }}:
        linux:
          os: "linux"
          vmImage: "ubuntu-latest"
      windows:
        os: "windows"
        vmImage: "windows-latest"
  pool:
    vmImage: $(vmImage)
  steps:
  - template: build-template.yml
    parameters:
      projectToPublish: '**/PrintTool.csproj'
      artifactname: PrintTool-$(os)
